### ISSUE TITLE
Unable to install via brew on MacOS

### ISSUE THREAD

**Issue by sreenadhp** [zim-desktop-wiki/zim-desktop-wiki#1013]
I am [installing Zim on mac](https://github.com/zim-desktop-wiki/zim-desktop-wiki#mac-os-x), but failed. MacOS Mojave 10.14.6 + Homebrew 2.2.4.

> $ brew install zim
> Error: No available formula with the name "zim" 
> ==> Searching for a previously deleted formula (in the last month)...
> Warning: homebrew/core is shallow clone. To get complete history run:
>   git -C "$(brew --repo homebrew/core)" fetch --unshallow
> 
> zim was deleted from homebrew/core in commit 814255548:
>   zim: delete
>   Depends on deprecated pygtk and python 2
>   Closes https://github.com/Homebrew/homebrew-core/issues/48460.
>   Signed-off-by: Michka Popoff <michkapopoff@gmail.com>
> 
> To show the formula before removal run:
>   git -C "$(brew --repo homebrew/core)" show 814255548^:Formula/zim.rb
> 
> If you still use this formula consider creating your own tap:
>   https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

What do I do?

**Comment by bgmilne** [comment]
It was incorrectly deleted.

See https://github.com/Homebrew/homebrew-core/pull/50054 for my attempt so far to get it back.

**Comment by bgmilne** [comment]
The pull request was merged, try now.

**Comment by stappersg** [comment]
@sreenadhp  ping

And do note that you have the power (and responsabilty) to close this issue. My reason for reminding you is because open issues do drain human energy, please prevent that. Thanks.

**Comment by sreenadhp** [comment]
Actually I am still unable to run/properly install zim.
I am getting the message that:
> zim 0.72.1_1 is already installed and up-to-date
But I am unable to run it. Other apps like keepassxc are facing issues since my latest security upgrade and I am not sure what is causing the issue: Mac, brew or zim. Also if zim's issue is similar to keepassxc. keepassxc was working well before the OS update, but zim never worked.

**Comment by bgmilne** [comment]
> Other apps like keepassxc are facing issues since my latest security upgrade and I am not sure what is causing the issue: Mac, brew or zim.

Sounds like a Mac OS problem, but could also be a Homebrew problem. Do you have a python3 interpreter installed? Where did you get it? Does it at least run (if you just type `python3 --version` into a terminal)?

With the required dependencies installed (via any mechanism), It should be possible to download zim from the github release, untar it, and run it in place. The homebrew package just ensures that all the other packages required for a good release are installed etc.

> Also if zim's issue is similar to keepassxc. keepassxc was working well before the OS update

How did you install keepassxc? What OS version were you running before, what OS version are you running after?

At least one of my colleagues installed zim from Homebrew after https://github.com/Homebrew/homebrew-core/pull/50054 was merged.

**Comment by kjyv** [comment]
Not sure if same reason but after updating to 0.72.1_1, this is happening:
(so looks like homebrew package issue)
$ zim
Traceback (most recent call last):
  File "/usr/local/bin/zim", line 50, in <module>
    import zim.main
  File "/usr/local/lib/python3.7/site-packages/zim/main/__init__.py", line 22, in <module>
    import zim.fs
  File "/usr/local/lib/python3.7/site-packages/zim/fs.py", line 27, in <module>
    from zim.signals import SignalEmitter, SIGNAL_AFTER
  File "/usr/local/lib/python3.7/site-packages/zim/signals.py", line 7, in <module>
    from gi.repository import GObject
ImportError: cannot import name 'GObject' from 'gi.repository' (unknown location)
ERROR: Could not find python module files in path:
/usr/local/bin /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python37.zip /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7 /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload /usr/local/lib/python3.7/site-packages /usr/local/Cellar/protobuf/3.11.4/libexec/lib/python3.7/site-packages

Try setting PYTHONPATH

**Comment by sreenadhp** [comment]
> How did you install keepassxc? What OS version were you running before, what OS version are you running after?

In installed keepassxc via brew. But when I did `brew list`, it was not listed (that was not the case earlier). So I just installed it again via brew.

Zim's issue is that I am able to install via brew, but not run it.

**Comment by bgmilne** [comment]
> zim 0.72.1_1 is already installed and up-to-date

It looks like https://github.com/Homebrew/homebrew-core/commit/eee9238b4ca0c18a7a2915fd288625caa5c62024 broke it on 30 March.

That doesn't seem to have been done with a PR, which would have validated that it built and ran correctly :-(.

I'll try and look at this later, but when I re-introduced the homebrew package, and the reviewers asked for Python3.8, I had to point out that the dependencies weren't building for Python3.8 yet.

**Comment by bgmilne** [comment]
See https://github.com/Homebrew/homebrew-core/pull/50054#discussion_r386222597

**Comment by sreenadhp** [comment]
> Homebrew/homebrew-core#50054 (comment)

I dont understand the issue. Is the issue that python3.8 is needed? I found an issue with [python@3.8](https://discourse.brew.sh/t/how-to-default-python-3-8-on-my-mac-using-homebrew/7050/2).

I just reinstalled:
> $ brew reinstall zim
> ==> Reinstalling zim 
> ==> Installing dependencies for zim: gettext, libffi, openssl@1.1, glib, pixman, icu4c, harfbuzz, librsvg, adwaita-icon-theme, gd, gtk+3, pkg-config, gobject-introspection and pygobject3
> ==> Installing zim dependency: gettext
> ==> Downloading https://homebrew.bintray.com/bottles/gettext-0.20.2_1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/52/52067198cab528f05fdc0b06f7b9711f7614f60a7361f1e764c4f46d3342ff22?__gda__=exp=1588004214~hmac=83
> ######################################################################## 100.0%
> ==> Pouring gettext-0.20.2_1.mojave.bottle.tar.gz
> ==> Caveats
> Emacs Lisp files have been installed to:
>   /usr/local/share/emacs/site-lisp/gettext
> ==> Summary
> 🍺  /usr/local/Cellar/gettext/0.20.2_1: 1,929 files, 18.7MB
> ==> Installing zim dependency: libffi
> ==> Downloading https://homebrew.bintray.com/bottles/libffi-3.3.mojave.bottle.tar.gz
> ######################################################################## 100.0%
> ==> Pouring libffi-3.3.mojave.bottle.tar.gz
> ==> Caveats
> libffi is keg-only, which means it was not symlinked into /usr/local,
> because macOS already provides this software and installing another version in
> parallel can cause all kinds of trouble.
> 
> For compilers to find libffi you may need to set:
>   export LDFLAGS="-L/usr/local/opt/libffi/lib"
>   export CPPFLAGS="-I/usr/local/opt/libffi/include"
> 
> For pkg-config to find libffi you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
> 
> ==> Summary
> 🍺  /usr/local/Cellar/libffi/3.3: 16 files, 484.8KB
> ==> Installing zim dependency: openssl@1.1
> ==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1g.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/5c/5c9d113393ff3efc95e5509175305fc9304fba35390a61915ed2864941c423f2?__gda__=exp=1588004235~hmac=cd
> ######################################################################## 100.0%
> ==> Pouring openssl@1.1-1.1.1g.mojave.bottle.tar.gz
> ==> Caveats
> A CA file has been bootstrapped using certificates from the system
> keychain. To add additional certificates, place .pem files in
>   /usr/local/etc/openssl@1.1/certs
> 
> and run
>   /usr/local/opt/openssl@1.1/bin/c_rehash
> 
> openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
> because macOS provides LibreSSL.
> 
> If you need to have openssl@1.1 first in your PATH run:
>   echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
> 
> For compilers to find openssl@1.1 you may need to set:
>   export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
>   export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
> 
> For pkg-config to find openssl@1.1 you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
> 
> ==> Summary
> 🍺  /usr/local/Cellar/openssl@1.1/1.1.1g: 8,059 files, 18MB
> ==> Installing zim dependency: glib
> ==> Downloading https://homebrew.bintray.com/bottles/glib-2.64.2_1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/4a/4ac9833acd0b2e6f8aa81bc426db78bcf2f4783f4788006d329d65c29b1bc561?__gda__=exp=1588004257~hmac=81
> ######################################################################## 100.0%
> ==> Pouring glib-2.64.2_1.mojave.bottle.tar.gz
> ==> Caveats
> Bash completion has been installed to:
>   /usr/local/etc/bash_completion.d
> ==> Summary
> 🍺  /usr/local/Cellar/glib/2.64.2_1: 436 files, 15.7MB
> ==> Installing zim dependency: pixman
> ==> Downloading https://homebrew.bintray.com/bottles/pixman-0.40.0.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/70/70a476e6b14fdfa42188d3df2797f8c13f25bd633528164b0d42c5fb70dfb431?__gda__=exp=1588004264~hmac=eb
> ######################################################################## 100.0%
> ==> Pouring pixman-0.40.0.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/pixman/0.40.0: 14 files, 1.3MB
> ==> Installing zim dependency: icu4c
> ==> Downloading https://homebrew.bintray.com/bottles/icu4c-66.1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/60/60e51b89507cf03f1d6ed59deda226b600f96f763dea9a415dfa8ebb42c197a0?__gda__=exp=1588004276~hmac=a1
> ######################################################################## 100.0%
> ==> Pouring icu4c-66.1.mojave.bottle.tar.gz
> ==> Caveats
> icu4c is keg-only, which means it was not symlinked into /usr/local,
> because macOS provides libicucore.dylib (but nothing else).
> 
> If you need to have icu4c first in your PATH run:
>   echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
>   echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc
> 
> For compilers to find icu4c you may need to set:
>   export LDFLAGS="-L/usr/local/opt/icu4c/lib"
>   export CPPFLAGS="-I/usr/local/opt/icu4c/include"
> 
> For pkg-config to find icu4c you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"
> 
> ==> Summary
> 🍺  /usr/local/Cellar/icu4c/66.1: 258 files, 70.3MB
> ==> Installing zim dependency: harfbuzz
> ==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-2.6.5_1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/ec/ecb10687976791aea5a31fa31fd52bbac7b2700c07ff4f1e6855f61125a624a1?__gda__=exp=1588004285~hmac=6f
> ######################################################################## 100.0%
> ==> Pouring harfbuzz-2.6.5_1.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/harfbuzz/2.6.5_1: 159 files, 11.3MB
> ==> Installing zim dependency: librsvg
> ==> Downloading https://homebrew.bintray.com/bottles/librsvg-2.48.4.mojave.bottle.1.tar.gz
> ==> Downloading from https://akamai.bintray.com/72/7262c196e991c6f700783b7eb1a5989d11973c444dbd0f281688a659250f77da?__gda__=exp=1588004292~hmac=ee
> ######################################################################## 100.0%
> ==> Pouring librsvg-2.48.4.mojave.bottle.1.tar.gz
> ==> /usr/local/opt/gdk-pixbuf/bin/gdk-pixbuf-query-loaders --update-cache
> 🍺  /usr/local/Cellar/librsvg/2.48.4: 47 files, 121.7MB
> ==> Installing zim dependency: adwaita-icon-theme
> ==> Downloading https://homebrew.bintray.com/bottles/adwaita-icon-theme-3.36.1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/68/68833a3f5aff79bdf75c2e761a8451750b93e8a955e49356a78a2a3f0e1fbcd8?__gda__=exp=1588004334~hmac=82
> ######################################################################## 100.0%
> ==> Pouring adwaita-icon-theme-3.36.1.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/adwaita-icon-theme/3.36.1: 6,042 files, 22.7MB
> ==> Installing zim dependency: gd
> ==> Downloading https://homebrew.bintray.com/bottles/gd-2.3.0.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/c0/c014efe5f692b3146a4416c0acdaad3c632064d50aad2c18598cfb32fb31ee69?__gda__=exp=1588004359~hmac=7f
> ######################################################################## 100.0%
> ==> Pouring gd-2.3.0.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/gd/2.3.0: 34 files, 1.1MB
> ==> Installing zim dependency: gtk+3
> ==> Downloading https://homebrew.bintray.com/bottles/gtk+3-3.24.18.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/6c/6ce65776c75f94af41427b82fa4bcc007b0b4be601e9ebba4620de59fd6e8139?__gda__=exp=1588004368~hmac=5a
> ######################################################################## 100.0%
> ==> Pouring gtk+3-3.24.18.mojave.bottle.tar.gz
> ==> /usr/local/opt/glib/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
> ==> /usr/local/Cellar/gtk+3/3.24.18/bin/gtk3-update-icon-cache -f -t /usr/local/share/icons/hicolor
> ==> /usr/local/Cellar/gtk+3/3.24.18/bin/gtk-query-immodules-3.0 > /usr/local/lib/gtk-3.0/3.0.0/immodules.cache
> 🍺  /usr/local/Cellar/gtk+3/3.24.18: 714 files, 53.1MB
> ==> Installing zim dependency: pkg-config
> ==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2_3.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/0d/0d14b797dba0e0ab595c9afba8ab7ef9c901b60b4f806b36580ef95ebb370232?__gda__=exp=1588004382~hmac=3b
> ######################################################################## 100.0%
> ==> Pouring pkg-config-0.29.2_3.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/pkg-config/0.29.2_3: 11 files, 623.6KB
> ==> Installing zim dependency: gobject-introspection
> ==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.64.1_1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/84/848dae21878e2178b8b93730b84633e41fd4fe3163cb51d1fb0c33dbc46511d4?__gda__=exp=1588004386~hmac=62
> ######################################################################## 100.0%
> ==> Pouring gobject-introspection-1.64.1_1.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/gobject-introspection/1.64.1_1: 189 files, 12.2MB
> ==> Installing zim dependency: pygobject3
> ==> Downloading https://homebrew.bintray.com/bottles/pygobject3-3.36.0_2.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/3c/3c9b34d60ebfa6bafbcf950690794fbd047b42fdf20614f5178d7460a2c8b5ab?__gda__=exp=1588004395~hmac=cf
> ######################################################################## 100.0%
> ==> Pouring pygobject3-3.36.0_2.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/pygobject3/3.36.0_2: 38 files, 924.4KB
> ==> Installing zim
> ==> Downloading https://homebrew.bintray.com/bottles/zim-0.72.1_1.mojave.bottle.tar.gz
> Downloading from https://akamai.bintray.com/0f/0fe8bbcf6c161c62dad791f42dea75495d9cf0b9e21822d8c6a7b5bbe6e0ab92?__gda__=exp=1588005162~hmac=aa
> ######################################################################## 100.0%
> ==> Pouring zim-0.72.1_1.mojave.bottle.tar.gz
> 🍺  /usr/local/Cellar/zim/0.72.1_1: 474 files, 5.8MB
> ==> Caveats
> ==> gettext
> Emacs Lisp files have been installed to:
>   /usr/local/share/emacs/site-lisp/gettext
> ==> libffi
> libffi is keg-only, which means it was not symlinked into /usr/local,
> because macOS already provides this software and installing another version in
> parallel can cause all kinds of trouble.
> 
> For compilers to find libffi you may need to set:
>   export LDFLAGS="-L/usr/local/opt/libffi/lib"
>   export CPPFLAGS="-I/usr/local/opt/libffi/include"
> 
> For pkg-config to find libffi you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
> 
> ==> openssl@1.1
> A CA file has been bootstrapped using certificates from the system
> keychain. To add additional certificates, place .pem files in
>   /usr/local/etc/openssl@1.1/certs
> 
> and run
>   /usr/local/opt/openssl@1.1/bin/c_rehash
> 
> openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
> because macOS provides LibreSSL.
> 
> If you need to have openssl@1.1 first in your PATH run:
>   echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
> 
> For compilers to find openssl@1.1 you may need to set:
>   export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
>   export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
> 
> For pkg-config to find openssl@1.1 you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
> 
> ==> glib
> Bash completion has been installed to:
>   /usr/local/etc/bash_completion.d
> ==> icu4c
> icu4c is keg-only, which means it was not symlinked into /usr/local,
> because macOS provides libicucore.dylib (but nothing else).
> 
> If you need to have icu4c first in your PATH run:
>   echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
>   echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc
> 
> For compilers to find icu4c you may need to set:
>   export LDFLAGS="-L/usr/local/opt/icu4c/lib"
>   export CPPFLAGS="-I/usr/local/opt/icu4c/include"
> 
> For pkg-config to find icu4c you may need to set:
>   export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"

In the lines asking me to `>> ~/.zshrc`:
- do I need to do it all
- I have zshell installed, but I am using bash. Is zshell needed for Zim to function?

> $ brew info zim
> zim: stable 0.72.1 (bottled), HEAD
> Graphical text editor used to maintain a collection of wiki pages
> https://zim-wiki.org/
> /usr/local/Cellar/zim/0.72.1_1 (474 files, 5.8MB) *
>   Poured from bottle on 2020-04-27 at 20:08:03
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/zim.rb
> ==> Dependencies
> Build: pkg-config ✔
> Required: adwaita-icon-theme ✔, graphviz ✔, gtk+3 ✔, gtksourceview3 ✔, pygobject3 ✔, python@3.8 ✔
> ==> Options
> --HEAD
> 	Install HEAD version
> ==> Analytics
> install: 266 (30 days), 504 (90 days), 2,056 (365 days)
> install-on-request: 266 (30 days), 503 (90 days), 2,049 (365 days)
> build-error: 0 (30 days)

What does `python@3.8 ✔` mean?  I wasn't able to run `python@3.8`, is that an issue?

> $ python@3.8 --version
> -bash: python@3.8: command not found
> $ python3 --version
> Python 3.7.7

**Comment by bgmilne** [comment]
> I dont understand the issue. Is the issue that python3.8 is needed?

Homebrew is/was busy switching Python from 3.7 to 3.8, and since zim was switched to use Python 3.8, some users have had difficulty running zim after installation, possibly due to dependencies having been packaged slightly differently or been reorganised for Python 3.8.

> do I need to do it all

Note that the messages you were referring to were specific to the icu4c package, not zim.

> I have zshell installed, but I am using bash. Is zshell needed for Zim to function?

No, the zim launcher script (`/usr/local/bin/zim`) uses the system-installed bash (`/bin/bash`), and doesn't require zsh or Homebrew's bash version, and sets up all required paths so zim should be able to start (assuming all dependencies are installed).

> What does python@3.8 ✔ mean? 

The @ is kind of a hack to allow multiple versions of the same software to be installed via Homebrew simultaneously.

> I wasn't able to run python@3.8, is that an issue?

`brew list python@3.8` may provide the answer you want here, but it's unrelated.

The only relevant question is, can you run `zim`, and if not, what error do you get, and can you resolve the error by installing additional packages.

(I don't really want to mess with this right now, as I need zim to be working, and I don't have time to troubleshoot these issues this week)

**Comment by sreenadhp** [comment]
I just discovered that zim is a cli application in Mac. I was trying to open zim via spotlight. Its missing `zim.app`. Plus I missed that I installed it via `brew install` instead of `brew cask install` which is for GUI apps.

**Comment by bgmilne** [comment]
> I just discovered that zim is a cli application in Mac.

Uh, it's a GUI application, but Mac OS has very poor support for GUIs that can be started purely by execution of an executable binary or executable script (compared to all other Unix implementations or Unix-like systems I have used).

>  I was trying to open zim via spotlight. Its missing `zim.app`. Plus I missed that I installed it via `brew install` instead of `brew cask install` which is for GUI apps.

Not necessarily, see above.

> I [fixed the issue of missing `zim.app`](https://github.com/jaap-karssenberg/zim-wiki/wiki/Mac-OSX-App-(wrapper)).

Maybe it makes sense to add this to the formula, or a script that allows the user to conveniently enable it? I could probably do it.

I assume your installation works now?

(I have since re-installed, and zim works for me where a previous attempt with Python@3.8 before my PR was merged had failed)
```
$ brew info zim
zim: stable 0.72.1 (bottled), HEAD
Graphical text editor used to maintain a collection of wiki pages
https://zim-wiki.org/
/usr/local/Cellar/zim/0.72.1_1 (578 files, 7.3MB) *
  Poured from bottle on 2020-05-01 at 17:18:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/zim.rb
==> Dependencies
Build: pkg-config ✔
Required: adwaita-icon-theme ✔, graphviz ✔, gtk+3 ✔, gtksourceview3 ✔, pygobject3 ✔, python@3.8 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 273 (30 days), 553 (90 days), 2,061 (365 days)
install-on-request: 273 (30 days), 552 (90 days), 2,054 (365 days)
build-error: 0 (30 days)
```

**Comment by sreenadhp** [comment]
Yes, it works.
