### ISSUE TITLE
Zim fails to build with Python 3.9: imports abc from collections

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#1005]
https://bugzilla.redhat.com/show_bug.cgi?id=1791740

Zim fails to build with Python 3.9.0a2.
```
+ ./setup.py build
Traceback (most recent call last):
  File "/builddir/build/BUILD/zim-0.72.0/./setup.py", line 25, in <module>
    import makeman # helper script
  File "/builddir/build/BUILD/zim-0.72.0/makeman.py", line 13, in <module>
    from zim.main import HelpCommand
  File "/builddir/build/BUILD/zim-0.72.0/zim/main/__init__.py", line 24, in <module>
    import zim.config
  File "/builddir/build/BUILD/zim-0.72.0/zim/config/__init__.py", line 10, in <module>
    from .dicts import *
  File "/builddir/build/BUILD/zim-0.72.0/zim/config/dicts.py", line 35, in <module>
    from zim.utils import OrderedDict
  File "/builddir/build/BUILD/zim-0.72.0/zim/utils.py", line 191, in <module>
    class OrderedDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"The abstract base classes in collections.abc no longer are exposed in the regular collections module. This will help create a clearer distinction between the concrete classes and the abstract base classes."

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.9/fedora-rawhide-x86_64/01148317-Zim/
