### ISSUE TITLE
.7 rc3 : default plugin link map doesn't wok

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#702]

**Comment by quesada** [comment]
ERROR: Exception while loading plugin: linkmap
Traceback (most recent call last):
  File "/home/quesada/bin/zim-desktop-wiki/zim/plugins/__init__.py", line 361, in load_plugins_from_preferences
    self.load_plugin(name)
  File "/home/quesada/bin/zim-desktop-wiki/zim/plugins/__init__.py", line 464, in load_plugin
    raise AssertionError('Dependencies failed for plugin %s' % name)
AssertionError: Dependencies failed for plugin linkmap

**Comment by Osndok** [comment]
Do you have graphviz installed?

**Comment by quesada** [comment]
yes, it works with .68.

**Comment by jaap-karssenberg** [comment]
As of 0.70 you also need to install the "xdot" application. Previous we packaged in inside zim, but now it is available as separate package.
If you look at the description in preferences dialog it should also show you what dependencies are not satisfied.

**Comment by stevphie** [comment]
xdot installed with pip.. still failed on plugins tab on windows

**Comment by AddendaDan** [comment]
> xdot installed with pip.. still failed on plugins tab on windows
> 
> edit: No matter what I do, it just won't detected xdot installed from pip

Apologies to bump this but having the same exact issue.  Installed xdot from pip, but still stuck with the xdot dependency failed on Link Map.

**Comment by stevphie** [comment]
> 
> 
> > xdot installed with pip.. still failed on plugins tab on windows
> > edit: No matter what I do, it just won't detected xdot installed from pip
> 
> Apologies to bump this but having the same exact issue. Installed xdot from pip, but still stuck with the xdot dependency failed on Link Map.

The problem is with xdot package from pip on windows. It's broken on python 3.7 (at least on my machine). To test this you can try execute xdot from command prompt with the given example files.

**Comment by victorfeight** [comment]
> > > xdot installed with pip.. still failed on plugins tab on windows
> > > edit: No matter what I do, it just won't detected xdot installed from pip
> > 
> > 
> > Apologies to bump this but having the same exact issue. Installed xdot from pip, but still stuck with the xdot dependency failed on Link Map.
> 
> The problem is with xdot package from pip on windows. It's broken on python 3.7 (at least on my machine). To test this you can try execute xdot from command prompt with the given example files.
> 
> EDIT: Apparently it's a known issue for python >3.6. I managed to made this work simply by installing xdot package downloaded from git
> 
> [jrfonseca/xdot.py#70](https://github.com/jrfonseca/xdot.py/issues/70)
> 
> you can use the given solution if you want to, but nothing work for me

I was able to get xdot working externally using Git SDK 64-bit and installing requiring components, and running from source tree, but Zim still does not recognize xdot. Does your zim recognize it and if so can you show steps you took to get Link Mapper working?

**Comment by frogmouse** [comment]
It seems time to bump this “closed” ticket.  It’s been four more months and this problem still exists. 

I have followed all the trails around and through this briar patch and I can testify that this plugin will **not** work in Windows 10.  The root problem seems to be that the Windows version of _xdot_ cannot find module _gi_ even though it is a part of _graphviz_ which **is** present.  Windows does not pass this error back to a user who runs _xdot_ from the command line, but Zim is smart enough to know that _xdot_ isn’t functional. There seems to be no effort to resolve this problem on the part of the developer, who has mostly abandoned _xdot_.  So the plugin is unlikely to **ever** work under windows.  

How about in WSL you ask?  There _xdot_ seems to work on Ubuntu 20.04 from the console, but Win 10 isn’t happy with _x_ or _wayland_, so I haven’t managed to get a graphical desktop up to test Zim there.  Maybe Win 11 users will have more success: graphic support is supposed to be built in.

There **is** a workaround – a bit kludgy, but functional:  create a vm on Windows.  Populate it with a recent linux, define the folder containing your Zim notebook as a shared directory. Install Zim and the plugin’s dependencies (graphviz and xdot), and install the plugin in Zim.  This works using VirtualBox.

I think is would be good if M. Karssenberg would add a note to the description of the plugin mentioning that it doesn't work in Windows because of upstream problems.  That would be a help to future users.

**Comment by introt** [comment]
@frogmouse please open a new ticket for this, thanks!

**Comment by frogmouse** [comment]
Done.  Thank you.
