### ISSUE TITLE
Sourceview code blocks rendering is often messed up since 0.74.0

### ISSUE THREAD

**Issue by pdecat** [zim-desktop-wiki/zim-desktop-wiki#1693]
**Describe the bug**

When a page has several sourceview blocks, the rendering is often broken. The more code blocks are present, the more rendering is broken.  

**To Reproduce**
1. Create a page with the following content:
```
Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2019-10-07T09:58:55+02:00

====== Git ======

===== Ignoring mass reformatting commits with git blame =====
https://akrabat.com/ignoring-revisions-with-git-blame/

===== Ignore files =====

==== Not managed by git ====
{{{code: lang="sh" linenumbers="False"
echo $file >> .git/info/exclude
}}}

See https://stackoverflow.com/questions/22906851/when-would-you-use-git-info-exclude-instead-of-gitignore-to-exclude-files

==== Already managed by git ====

=== You want to keep your local changes ===
 Exclude files should change locally from the management of Git:
{{{code: lang="sh" linenumbers="False"
git update-index --skip-worktree $file
git ls-files -v | grep ^S
}}}

Undo with:
{{{code: lang="sh" linenumbers="False"
git update-index --no-skip-worktree $file
}}}

=== You don't mind loosing your changes at some times ===
Exclude files should **not** change locally from the management of Git:
{{{code: lang="sh" linenumbers="False"
git update-index --assume-unchanged $file
git ls-files -v | grep ^h
}}}

Undo with:
{{{code: lang="sh" linenumbers="False"
git update-index --no-assume-unchanged $file
}}}

See https://dev.to/nishina555/how-to-ignore-files-already-managed-with-git-locally-19oo

===== Show first commit =====
{{{code: lang="sh" linenumbers="False"
git log $(git rev-list --max-parents=0 HEAD)
}}}


===== Release go app to github =====
{{{code: lang="sh" linenumbers="False"
GITHUB_TOKEN=$(gopass websites/github.com/goreleaser|head -n1) goreleaser
}}}


===== Checkout pull request branch from Bitbucket =====
**Not supported by Bitbucket Cloud at the moment!**
{{{code: lang="sh" linenumbers="False"
git fetch upstream refs/pull-requests/$ID/from:pr-$ID
}}}


===== Checkout pull request branch from Github =====
{{{code: lang="sh" linenumbers="False"
git fetch upstream pull/$ID/head:pr-$ID
}}}


===== Checkout merge request branch from Gitlab =====
{{{code: lang="sh" linenumbers="False"
git fetch upstream merge-requests/$ID/head:mr-$ID
}}}


===== Trace git commands =====
{{{code: lang="sh" linenumbers="False"
export GIT_TRACE=1
}}}

Note: 1 is the file descriptor id

===== Search differences =====
{{{code: lang="sh" linenumbers="False"
git log -p -S $string
git log -p -G $regexp
}}}


===== Search all commits =====
{{{code: lang="sh" linenumbers="False"
git grep <regexp> $(git rev-list --all)
}}}


===== Diff/apply without prefix =====
Setup:
{{{code: lang="sh" linenumbers="False"
git config --global diff.noprefix true
}}}

Then:
{{{code: lang="sh" linenumbers="False"
git apply -p0
}}}


===== Git rebase fixup autosquash =====
Set
{{{code: lang="sh" linenumbers="False"
git config --global rebase.autosquash true
}}}

Then
{{{code: lang="sh" linenumbers="False"
git commit --fixup bbb2222 # or git commit --fixup :/stringfromcommittofix
git rebase --interactive bbb2222~1
}}}

https://thoughtbot.com/blog/autosquashing-git-commits


===== Amend author =====
{{{code: lang="sh" linenumbers="False"
git commit --amend --author "Patrick Decat <pdecat@gmail.com>
}}}


===== Git contributors statistics =====
{{{code: lang="sh" linenumbers="False"
git shortlog -s -e -c -n
}}}

https://stackoverflow.com/a/54113307/316805
```
2. Navigate to another page
3. Come back to the page with several code blocks
4. See broken rendering

Moving the focus to another page then coming back does not help.

Note: I just noticed that moving the focus to another window makes the zim page re-render properly.

**Expected behavior**

Rendering should be perfect ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/318490/137977683-3e00b988-d30f-40bf-964a-8b6ba361ad9a.png)

**Environment (please complete the following information):**
 - Version -- 0.74.0 to 0.74.2
 - OS: Ubuntu Linux 21.10 (but same occurred with 21.04)
 - Language: forced English locale, but same in French locale.

**Additional context**

Same behavior with gtksourceview 3 & 4 (I uninstalled v3 for my tests).

No warning or error in debug log.

As mentioned in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1591#issuecomment-946152956, 
I've bisected the issue to come from https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/b64f7edd77393fb19b321d7ee1b789515977fb78

```
# git bisect log
# bad: [a532c35e4b54c8fa1823a483dc005e9f52865e7e] Release 0.74.0
# good: [1ace8e5006655434602f96b6f3ba391e1d34e99a] Release 0.73.5
git bisect start '0.74.0' '0.73.5'
# bad: [2f0f3ce634c42f6eb4aaa148bd827e7ffbf5ca0f] Update insert_line documentation
git bisect bad 2f0f3ce634c42f6eb4aaa148bd827e7ffbf5ca0f
# bad: [63047e3eda7dd8679ac5ae54e31f99a5b73b80e4] Add default browser to preferences
git bisect bad 63047e3eda7dd8679ac5ae54e31f99a5b73b80e4
# bad: [018c99bece330f071ec43ab17dc3e79b391278ce] Fix test to pass on Travis
git bisect bad 018c99bece330f071ec43ab17dc3e79b391278ce
# bad: [018c99bece330f071ec43ab17dc3e79b391278ce] Fix test to pass on Travis
git bisect bad 018c99bece330f071ec43ab17dc3e79b391278ce
# good: [5be94c5fc85f010c6446b8047ddaf4ab7be15521] Fix regression with pages with formatting in heading
git bisect good 5be94c5fc85f010c6446b8047ddaf4ab7be15521
# bad: [b64f7edd77393fb19b321d7ee1b789515977fb78] Move ownership of TextBuffer to Page object
git bisect bad b64f7edd77393fb19b321d7ee1b789515977fb78
# bad: [b64f7edd77393fb19b321d7ee1b789515977fb78] Move ownership of TextBuffer to Page object
git bisect bad b64f7edd77393fb19b321d7ee1b789515977fb78
# good: [09fc68157a0815f4c85ed39842630529b01db2a8] Release 0.73.2
git bisect good 09fc68157a0815f4c85ed39842630529b01db2a8
# good: [918e550b3446b77a573e9dbbd948f1b8ecac4f50] Fixup b8d5caab485c38d898bae483821f39f0a6233644
git bisect good 918e550b3446b77a573e9dbbd948f1b8ecac4f50
# good: [9f64f44d753bac828e359285470a3c370605e1bb] Show link destination for keyboard navigation fixes #452, closes #707
git bisect good 9f64f44d753bac828e359285470a3c370605e1bb
# good: [9808183182638276ad1e4dd8ff204b05a65320ac] Use code font in style config for sourceview
git bisect good 9808183182638276ad1e4dd8ff204b05a65320ac
# good: [d1ce936683b740007bf178a07cf62f0c012477b1] Remove custom WeakSet in favor of weakref.WeakSet
git bisect good d1ce936683b740007bf178a07cf62f0c012477b1
# first bad commit: [b64f7edd77393fb19b321d7ee1b789515977fb78] Move ownership of TextBuffer to Page object
```

Note: during this `git bisect` run, I had to cherry-pick https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/0c7d355a76236b0c687fb7c59cd974c2c7f35657 
to avoid `AttributeError: 'ElementTree' object has no attribute 'getiterator'` errors as python 3.9 is the system version on Ubuntu 21.10.

**Comment by lorenrosen** [comment]
I'm also seeing a similar issue on my system, running 0.74.2, with this page. A few 
comments:
- For other reasons, I added a call (in an experimental local version of zim) to _hack_on_inserted_tree, which partially (but not completely) helps. I'll give details separately.
- With the Table of Contents enabled (default settings), the TOC interleaved with the page text. I'll file a separate bug if need be.

**Comment by hsandt** [comment]
Hey, I regularly get screentearing on normal text, not even code blocks, after scrolling:

![Zim bug page tearing (only relevant part)](https://user-images.githubusercontent.com/1067772/170693005-ba7724b8-f0ed-42b7-9bb0-f1714c50c8bd.png)

Is it the same bug or should I open another one?

It's the number one issue I have with Zim, that requires me to either highlight all text to refresh, or switch to another note and back again to refresh. I didn't try the zoom out/zoom in but it should work too.

**Comment by vossenjp** [comment]
> Hey, I regularly get screentearing on normal text, not even code blocks, after scrolling:

I still have the same problem (Mint PPA versions), not on Mac, and it's still really frustrating.  **My clumsy hack-around** is to hit PgUp 2 or 3 times, them PgDn the same number of times to refresh.  Only 1 PgUp/Dn doesn't work and sometimes 2 doesn't either.  CTRL-R can also help, but on my limited resource nodes that can take many tens of seconds so is unacceptable.

**Comment by brainbow1** [comment]
@jaap-karssenberg : 
Right now I use zim in version 0.73.5-1 as it is the last version version that worked without those rendering issues. I use it with Debian bullseye (stable).
In the Debian repos there is available:
0.73.5-1 for bullseye/stable
0.74.3-1 for bookworm/testing (becomes stable till the end of the year I think)
0.75.1-1 for sid/unstable

If there is a version after my current 0.73.5-1 available that has overcome those rendering issues, I would like to use it when I upgrade to debian bookworm as soon as its stable... 

Which version would u recommend to use, to avoid those rendering problems?

**Comment by introt** [comment]
@brainbow1 0.74.3 and later should contain the partial fix, but if you're still getting the rendering issues you can keep using 0.73.5 - if you're unable to install it from oldstable repos or the PPA, you can run it from [source](https://github.com/zim-desktop-wiki/zim-desktop-wiki/releases/tag/0.73.5) (no compilation required, just point your launcher at zim.py using eg. menulibre)

**Comment by xvusrmqj** [comment]
@jaap-karssenberg : still getting the render issues using 0.75.1 on windows OS.  when a codeblock height large than a screen. scroll down and up can reproduce it .
![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/2316516/34f0e616-7338-4b05-a110-e72b3aea4ec2)
