### ISSUE TITLE
Bug found / regression 0.74.3 ->0.75.0

### ISSUE THREAD

**Issue by menthalo37** [zim-desktop-wiki/zim-desktop-wiki#2183]
**Bug description**
(see also Discussions > uml diagram editor #2181 ) 

I get a bug in 0.75.0 with plantuml (umldiagrameditor.py plugin works well in 0.74.3 and not in 0.75.0); is it possible to check if it might be a regression which could need a patch/correction/update of 0.75.0 ?
Thanks.

...... message : 
```
This is zim 0.75.0
Platform: nt
Locale: fr_FR cp1252
FS encoding: utf-8
Python: (3, 10, 7, 'final', 0)
PyGObject: (3, 42, 1)

...Traceback...
  File "zim/gui/insertedobjects.py", line 437, in _action_handler
  File "zim/plugins/base/imagegenerator.py", line 57, in new_model_interactive
  File "zim/insertedobjects.py", line 83, in _model_from_data_wrapper
  File "zim/plugins/base/imagegenerator.py", line 84, in model_from_data
  File "zim/plugins/base/imagegenerator.py", line 182, in __init__
  File "zim/newfs/base.py", line 500, in new_file
  File "zim/newfs/base.py", line 530, in _new_child
  File "zim/plugins/base/imagegenerator.py", line 178, in check_image_file
  File "zim/plugins/base/imagegenerator.py", line 212, in _stitch_fileextension
AttributeError: 'NoneType' object has no attribute 'rfind'
```
.....
**To Reproduce**
1. install zim (either 0.74.3 or 0.75.0, portable mode both, from exe for Win x64 given on official download Zim Notes site)
2. follow instructions given for umldiagrameditor.py plugin installation ( [https://gitlab.com/Voyvode/zim-umldiagrameditor/-/blob/master/README.adoc](https://gitlab.com/Voyvode/zim-umldiagrameditor/-/blob/master/README.adoc) )
3. modify PATH in environment variables (within windows) "for my personal account only", adding/including where plantuml.jar is stored (rename plantuml-x.xxxxx.jar before if needed in juste "plantuml.jar")
4. once zim is running, try to add greffon UML diagram
5. (it works on both 0.74.3 and 0.75 versions)
6. insert UML Diagram works ONLY in 0.74.3 version and NOT for 0.75.0 version (see error message pasted before)

**Expected behavior**
Why does it not work on 0.75.0 Zim version ?

**Environment (please complete the following information):**
Windows 10

**Additional context**
after portable installation

**Comment by jaap-karssenberg** [comment]
Please also report to the plugin itself; may need to be updated to work
with latest zim version.

**Comment by menthalo37** [comment]
Done : see [https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2]( https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2)

Moreover, I must precise I had to change dotcmd value thus (in 0.74.3 in order to make the plugin work) 

```
# TODO put these commands in preferences
#dotcmd = ('plantuml')
dotcmd = ('java', '-jar' ,r'D:\Documents_E\_zim_testzone1\plantuml\plantuml.jar')

```

**Comment by menthalo37** [comment]
Moreover : I precise both "graphviz" and "equation" plugins work properly, within 0.75.0 Zim version (of course after appropriate path variable modification, inside Windows).
So only "plantuml" plugin still doesn't work ( error message is shown before any text input window appears )

**Comment by menthalo37** [comment]
One solution Found ! 
Even if my python understanding is very poor, after lot of tests, here is why "uml diagram editor" didn't work : 

`imagefile_extension = '.png' `  line
**must be included in "class PlantumlGenerator(ImageGeneratorClass):"** part
and not in "class BackwardPlantumlImageObjectType(BackwardImageGeneratorObjectType):" part

Same adaptation can be seen in "classic" plugins integrated in zim (such as diagram graphviz insertion) : see this commit
[https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/55ab6f2b69ee3e745bd267e56f11a53b7ad10aa3#diff-da5ad2e4e158ad4987acb4ba2616d16c439fc925fe822c1b0d71ab47ec571a19](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commit/55ab6f2b69ee3e745bd267e56f11a53b7ad10aa3#diff-da5ad2e4e158ad4987acb4ba2616d16c439fc925fe822c1b0d71ab47ec571a19)

I report this resolution on [https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2](https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2)

Thanks.

**Comment by prahal** [comment]
May you close this issue?
The issue has been reported to be in the plugin and a fix has been merged a few hours ago: https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2#note_1130079425

**Comment by menthalo37** [comment]
closed as said [https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2#note_1130079425](https://gitlab.com/Voyvode/zim-umldiagrameditor/-/issues/2#note_1130079425)
