### ISSUE TITLE
Zim fails to build with Python 3.9: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#1032]
https://bugzilla.redhat.com/show_bug.cgi?id=1808656

Zim fails to build with Python 3.9.0a4.

Traceback (most recent call last):
  File "/builddir/build/BUILD/zim-0.72.0/./setup.py", line 301, in <module>
    setup(
  File "/usr/lib64/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/builddir/build/BUILD/zim-0.72.0/./setup.py", line 220, in run
    build_class.run(self)
  File "/usr/lib64/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/builddir/build/BUILD/zim-0.72.0/./setup.py", line 193, in run
    msgfmt.make(pofile, mofile)
  File "/builddir/build/BUILD/zim-0.72.0/msgfmt.py", line 199, in make
    output = generate()
  File "/builddir/build/BUILD/zim-0.72.0/msgfmt.py", line 92, in generate
    output += array.array("i", offsets).tostring()
AttributeError: 'array.array' object has no attribute 'tostring'

See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"array.array: tostring() and fromstring() methods have been removed. They were aliases to tobytes() and frombytes(), deprecated since Python 3.2."

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.9/fedora-rawhide-x86_64/01257944-Zim/

For all our attempts to build Zim with Python 3.9, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.9/package/Zim/

Testing and mass rebuild of packages is happening in copr. You can follow these instructions to test locally in mock if your package builds with Python 3.9:
https://copr.fedorainfracloud.org/coprs/g/python/python3.9/

Let us know here if you have any questions.

Python 3.9 will be included in Fedora 33. To make that update smoother, we're building Fedora packages with early pre-releases of Python 3.9.
A build failure prevents us from testing all dependent packages (transitive [Build]Requires), so if this package is required a lot, it's important for us to get it fixed soon.
We'd appreciate help from the people who know this package best, but if you don't want to work on this now, let us know so we can try to work around it on our side.

**Comment by lcabrini** [comment]
Python 3.9.0a4? Wouldn't this likely be more an issue with an alpha release of Python than with Zim. Perhaps it would make more sense to try to build once Python 3.9 has stabilized a bit.

**Comment by jaap-karssenberg** [comment]
@lcabrini the description refers to python documentation indicating that this is an intentional change in python - so not an issue that will be resolved by waiting for future builds
